version: "3"
services:
  selenium-hub:
    image: infydp.ad.infosys.com:8082/selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: infydp.ad.infosys.com:8082/selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  firefox:
    image: infydp.ad.infosys.com:8082/selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444